### ISSUE TITLE
Update examples to mzQC v1.0

### ISSUE THREAD

**Issue by bittremieux** [HUPO-PSI/mzQC#225]
We need to make sure that the [examples on the website](https://hupo-psi.github.io/mzQC/examples/) are fully complaint with the official mzQC v1.0 specification.

Examples to update:

- [x] [Single run](https://hupo-psi.github.io/mzQC/examples/intro_run/) @bittremieux 
- [x] [Multi-run](https://hupo-psi.github.io/mzQC/examples/set-of-runs/) @bittremieux #219
- [ ] [QC example](https://hupo-psi.github.io/mzQC/examples/QC2-sample-example/) @mwalzer #231 
- [x] [mzQC in mzML](https://hupo-psi.github.io/mzQC/examples/mzml-mzqc-example/) @bittremieux #228 
- [x] [USI for mzQC](https://hupo-psi.github.io/mzQC/examples/USI-example/) @cbielow #229 
- [ ] [Metabolomics batch correction](https://hupo-psi.github.io/mzQC/examples/metabo-batches/) @nilshoffmann #233

New examples to add:
- [ ] Interoperability between SDRF and mzQC

Procedure to ensure that the examples are valid:

- The full mzQC file successfully passes validation with our validator.
- The mzQC snippets in the corresponding markdown file are updated accordingly.
- The description in the markdown file is accurate and informative.

Nice to have:

- Pretty format the mzQC JSON content (indentation 2 spaces).
- Format the markdown page to have each sentence start on a new line (for convenient git diffs)

**Comment by mwalzer** [comment]
@mwalzer TLC for open (old) PRs

**Comment by mwalzer** [comment]
I made some updates to the pymzqc lib that might be helpful to this and future issues of the type:
* You can now easily call the local validator via mzqc-validator, 
* You can fix missing descriptions to (otherwise valid) mzQC skeletons - this will also do **prettyprint indentation**
see also [@readthedocs](https://pymzqc.readthedocs.io/en/v1.0.0rc3/accessories.html)
Install via:
`pip install -U git+https://github.com/MS-Quality-hub/pymzqc.git#v1.0.0rc3`
